format.

diff --git a/src/colatrl b/src/colatrl
--- a/src/colatrl
+++ b/src/colatrl
@@ -27,8 +27,8 @@ set -e
 set -u
 
 if [[ $(id -u) != 0 ]]; then
-  echo "Aborting, not root."
-  exit 0
+	echo "Aborting, not root."
+	exit 0
 fi
 
 SCRIPTDIR="${0%/*}"
@@ -40,164 +40,163 @@ declare -r TEST6=2001:4860:4860::8888
 
 # DNS fetch of 96-bit prefix
 pfx96() {
-  host -t AAAA ipv4only.arpa | sed -rn 's@^ipv4only[.]arpa has IPv6 address ([0-9a-f:]+)::c000:a[ab]@\1::@p' | sort -u
+	host -t AAAA ipv4only.arpa | sed -rn 's@^ipv4only[.]arpa has IPv6 address ([0-9a-f:]+)::c000:a[ab]@\1::@p' | sort -u
 }
 
 # IPv6 route lookup to a destination address, argument 1/2/3 to return GATEWAY, DEVICE, SRCIP
 gt() {
-  ip -6 route get "$1" | sed -rn 's@^.* via ([0-9a-f:]+) dev ([a-z0-9]+) .* src ([0-9a-f:]+) .*$@\'$2'@p'
+	ip -6 route get "$1" | sed -rn 's@^.* via ([0-9a-f:]+) dev ([a-z0-9]+) .* src ([0-9a-f:]+) .*$@\'$2'@p'
 }
 
 get_ipv4_default_route_device() {
-  ip -4 route get "${TEST4}" | sed -rn 's@^.* dev ([^ ]+) .*@\1@p'
+	ip -4 route get "${TEST4}" | sed -rn 's@^.* dev ([^ ]+) .*@\1@p'
 }
 
 get_ipv6_default_route_device() {
-  ip -6 route get "${TEST6}" | sed -rn 's@^.* dev ([^ ]+) .*@\1@p'
+	ip -6 route get "${TEST6}" | sed -rn 's@^.* dev ([^ ]+) .*@\1@p'
 }
 
 cmd_stop() {
-  declare -r DEV=$1
-  declare -r DEV4=$2
-  declare -r DEV6=$3
+	declare -r DEV=$1
+	declare -r DEV4=$2
+	declare -r DEV6=$3
 
-  tc filter del dev "${DEV6}" ingress || :
-  tc filter del dev "${DEV6}" egress || :
-  ip -6 neigh flush proxy dev "${DEV6}" || :
-  ip -4 addr del "${LOCAL4}/32" dev "${DEV4}" || :
-  tc qdisc del dev "${DEV}" clsact || :
-  echo 0 > "/proc/sys/net/ipv6/conf/${DEV}/proxy_ndp"
+	tc filter del dev "${DEV6}" ingress || :
+	tc filter del dev "${DEV6}" egress || :
+	ip -6 neigh flush proxy dev "${DEV6}" || :
+	ip -4 addr del "${LOCAL4}/32" dev "${DEV4}" || :
+	tc qdisc del dev "${DEV}" clsact || :
+	echo 0 >"/proc/sys/net/ipv6/conf/${DEV}/proxy_ndp"
 
-  return 0
+	return 0
 }
 
 cmd_status() {
-  declare -r DEV=$1
-  declare -r DEV4=$2
-  declare -r DEV6=$3
+	declare -r DEV=$1
+	declare -r DEV4=$2
+	declare -r DEV6=$3
 
-  echo "--- IPv6 route ---"
-  ip -6 route get "${TEST6}"
+	echo "--- IPv6 route ---"
+	ip -6 route get "${TEST6}"
 
-  echo "--- IPv4 route ---"
-  ip -4 route get "${TEST4}" || :
+	echo "--- IPv4 route ---"
+	ip -4 route get "${TEST4}" || :
 
-  echo "--- Detected ipv6/ipv4 default route via ${DEV6}/${DEV4}. ---"
+	echo "--- Detected ipv6/ipv4 default route via ${DEV6}/${DEV4}. ---"
 
-  echo "--- IP addr (non deprecated) ---"
-  ip addr show dev "${DEV6}" -deprecated
+	echo "--- IP addr (non deprecated) ---"
+	ip addr show dev "${DEV6}" -deprecated
 
-  echo "--- ip neigh proxy ${DEV6} ---"
-  ip -6 neigh show proxy dev "${DEV6}"
+	echo "--- ip neigh proxy ${DEV6} ---"
+	ip -6 neigh show proxy dev "${DEV6}"
 
-  echo "--- tc filter ${DEV6} ingress ---"
-  tc filter show dev "${DEV6}" ingress
+	echo "--- tc filter ${DEV6} ingress ---"
+	tc filter show dev "${DEV6}" ingress
 
-  echo "--- tc filter ${DEV6} egress ---"
-  tc filter show dev "${DEV6}" egress
+	echo "--- tc filter ${DEV6} egress ---"
+	tc filter show dev "${DEV6}" egress
 
-  echo "--- CLAT eBPF maps ---"
-  bpftool map | grep -E ' name clat_(ifmac|srcip|input|timer|output)_map ' || :
+	echo "--- CLAT eBPF maps ---"
+	bpftool map | grep -E ' name clat_(ifmac|srcip|input|timer|output)_map ' || :
 
-  echo
-  for map in ifmac srcip input timer output; do
-    echo -n "${map}: "
-    bpftool map dump name "clat_${map}_map" | tr '\n' ' ' | sed -r 's@  +@ @g'
-    echo
-  done
+	echo
+	for map in ifmac srcip input timer output; do
+		echo -n "${map}: "
+		bpftool map dump name "clat_${map}_map" | tr '\n' ' ' | sed -r 's@  +@ @g'
+		echo
+	done
 
-  echo "--- CLAT eBPF programs ---"
-  bpftool prog | grep -E ' name clat_(e|in)gress ' || :
+	echo "--- CLAT eBPF programs ---"
+	bpftool prog | grep -E ' name clat_(e|in)gress ' || :
 
+	timeout 1 cat /sys/kernel/debug/tracing/trace_pipe || :
 
-  timeout 1 cat /sys/kernel/debug/tracing/trace_pipe || :
-
-  return 0
+	return 0
 }
 
 cmd_start() {
-  declare -r DEV=$1
-  declare -r DEV4=$2
-  declare -r DEV6=$3
+	declare -r DEV=$1
+	declare -r DEV4=$2
+	declare -r DEV6=$3
 
-  declare -r PFX96=$(pfx96)
-  declare -r GW=$(gt "${PFX96}" 1)
-  declare -r SRC=$(gt "${PFX96}" 3)
-  declare -r IFINDEX=$(< "/sys/class/net/${DEV}/ifindex")
-  declare -r MAC=$(< "/sys/class/net/${DEV}/address")
-  declare -r MTU6=$(< "/proc/sys/net/ipv6/conf/${DEV}/mtu")
-  declare -r MTU4=$((MTU6-28))  # ipv6 header size - ipv4 header size = 20,  plus an extra 8 bytes for IPv6 Fragmentation Extension Header
-  declare -r HINT="$(${CLATUTIL} get "${DEV}" ${LOCAL4})"
+	declare -r PFX96=$(pfx96)
+	declare -r GW=$(gt "${PFX96}" 1)
+	declare -r SRC=$(gt "${PFX96}" 3)
+	declare -r IFINDEX=$(<"/sys/class/net/${DEV}/ifindex")
+	declare -r MAC=$(<"/sys/class/net/${DEV}/address")
+	declare -r MTU6=$(<"/proc/sys/net/ipv6/conf/${DEV}/mtu")
+	declare -r MTU4=$((MTU6 - 28)) # ipv6 header size - ipv4 header size = 20,  plus an extra 8 bytes for IPv6 Fragmentation Extension Header
+	declare -r HINT="$(${CLATUTIL} get "${DEV}" ${LOCAL4})"
 
-  # Calculate checksum neutral IPv6 CLAT source address.  Hint will be reused if valid.
-  declare -r CLATIP="$(${CLATUTIL} generate "${SRC}" "${PFX96}" "${LOCAL4}" "${HINT}")"
+	# Calculate checksum neutral IPv6 CLAT source address.  Hint will be reused if valid.
+	declare -r CLATIP="$(${CLATUTIL} generate "${SRC}" "${PFX96}" "${LOCAL4}" "${HINT}")"
 
-  if [[ "${CLATIP}" == "${HINT}" ]]; then
-    declare -r PREEXIST=true
-  else
-    declare -r PREEXIST=false
-  fi
+	if [[ "${CLATIP}" == "${HINT}" ]]; then
+		declare -r PREEXIST=true
+	else
+		declare -r PREEXIST=false
+	fi
 
-  echo 1 > "/proc/sys/net/ipv6/conf/${DEV}/proxy_ndp"
+	echo 1 >"/proc/sys/net/ipv6/conf/${DEV}/proxy_ndp"
 
-  tc qdisc add dev "${DEV}" clsact
-  tc filter add dev "${DEV}" ingress prio 1 protocol ipv6 bpf object-file "${CLAT}" section schedcls/clat_ingress direct-action
-  tc filter add dev "${DEV}"  egress prio 1 protocol arp  matchall action drop
-  tc filter add dev "${DEV}"  egress prio 2 protocol ip   bpf object-file "${CLAT}" section schedcls/clat_egress  direct-action
+	tc qdisc add dev "${DEV}" clsact
+	tc filter add dev "${DEV}" ingress prio 1 protocol ipv6 bpf object-file "${CLAT}" section schedcls/clat_ingress direct-action
+	tc filter add dev "${DEV}" egress prio 1 protocol arp matchall action drop
+	tc filter add dev "${DEV}" egress prio 2 protocol ip bpf object-file "${CLAT}" section schedcls/clat_egress direct-action
 
-  ip -4 addr replace "${LOCAL4}/32" dev "${DEV}"
+	ip -4 addr replace "${LOCAL4}/32" dev "${DEV}"
 
-  ${CLATUTIL} install "${IFINDEX}" "${DEV}" "${MAC}" "${MTU4}" "${CLATIP}" "${PFX96}" "${LOCAL4}"
+	${CLATUTIL} install "${IFINDEX}" "${DEV}" "${MAC}" "${MTU4}" "${CLATIP}" "${PFX96}" "${LOCAL4}"
 
-  ip -4 route add default via inet6 "${GW}" dev "${DEV}" mtu "${MTU4}" src "${LOCAL4}" metric 1
+	ip -4 route add default via inet6 "${GW}" dev "${DEV}" mtu "${MTU4}" src "${LOCAL4}" metric 1
 
-  if ! "${PREEXIST}"; then
-    echo "Triggering DAD for ${CLATIP}/128 on ${DEV}"
-    sleep 1
-    ip -6 addr add "${CLATIP}/128" dev "${DEV}"
-    sleep 2
-    # it may be enough to get the bpf program to also handle multicast packets
-    # do we need the router flag set on our NAs?
-    ndisc6 -1 -s "${CLATIP}" "${GW}" "${DEV}"
-    ip -6 addr del "${CLATIP}/128" dev "${DEV}"
-  fi
+	if ! "${PREEXIST}"; then
+		echo "Triggering DAD for ${CLATIP}/128 on ${DEV}"
+		sleep 1
+		ip -6 addr add "${CLATIP}/128" dev "${DEV}"
+		sleep 2
+		# it may be enough to get the bpf program to also handle multicast packets
+		# do we need the router flag set on our NAs?
+		ndisc6 -1 -s "${CLATIP}" "${GW}" "${DEV}"
+		ip -6 addr del "${CLATIP}/128" dev "${DEV}"
+	fi
 
-  ip -6 neigh add proxy "${CLATIP}" dev "${DEV}"
+	ip -6 neigh add proxy "${CLATIP}" dev "${DEV}"
 
-  ping -c 3 "${TEST4}"
-  return 0
+	ping -c 3 "${TEST4}"
+	return 0
 }
 
 process() {
-  declare -r CMD=$1
+	declare -r CMD=$1
 
-  if [[ "$CMD" == "" ]] ; then
-    echo Need start, stop, or status.
-    return 1
-  fi
+	if [[ "$CMD" == "" ]]; then
+		echo Need start, stop, or status.
+		return 1
+	fi
 
-  declare -r PFX96=$(pfx96)
-  declare -r DEV=$(gt "${PFX96}" 2)
-  declare -r DEV4=$(get_ipv4_default_route_device || echo unknown)
-  declare -r DEV6=$(get_ipv6_default_route_device)
+	declare -r PFX96=$(pfx96)
+	declare -r DEV=$(gt "${PFX96}" 2)
+	declare -r DEV4=$(get_ipv4_default_route_device || echo unknown)
+	declare -r DEV6=$(get_ipv6_default_route_device)
 
-  if [[ "$CMD" == "stop" ]] ; then
-    cmd_stop "${DEV}" "${DEV4}" "${DEV6}"
-    return 0
-  fi
+	if [[ "$CMD" == "stop" ]]; then
+		cmd_stop "${DEV}" "${DEV4}" "${DEV6}"
+		return 0
+	fi
 
-  if [[ "$CMD" == "status" ]] ; then
-    cmd_status "${DEV}" "${DEV4}" "${DEV6}"
-    return 0
-  fi
+	if [[ "$CMD" == "status" ]]; then
+		cmd_status "${DEV}" "${DEV4}" "${DEV6}"
+		return 0
+	fi
 
-  if [[ "$CMD" != "start" ]] ; then
-    echo Need start, stop, or status.
-    return 1
-  fi
+	if [[ "$CMD" != "start" ]]; then
+		echo Need start, stop, or status.
+		return 1
+	fi
 
-  cmd_start "${DEV}" "${DEV4}" "${DEV6}"
-  return 0
+	cmd_start "${DEV}" "${DEV4}" "${DEV6}"
+	return 0
 }
 
 process "$*"
